services:
  db:
    container_name: appliq-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appliq_loc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
        
  rabbit:
    container_name: appliq-rabbitmq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    ports:
      - '5672:5672'

volumes:
  pgdata:
